import { createFileRoute, Link } from "@tanstack/react-router";
import { ArrowRight, Building2, CheckCircle2, FileText, Search, Users } from "lucide-react";
import { useLanguage } from "../lib/i18n";

export const Route=createFileRoute("/")({component:Home});
function Home(){
 const {language}=useLanguage(); const pt=language==="pt";
 return <main>
  <section className="bg-gradient-to-br from-blue-700 via-blue-600 to-cyan-600 text-white"><div className="mx-auto grid max-w-7xl gap-10 px-4 py-20 md:grid-cols-[1.2fr_.8fr] md:items-center md:py-28">
   <div><span className="rounded-full bg-white/15 px-3 py-1 text-sm">Marketplace B2B Moçambique</span><h1 className="mt-6 text-4xl font-extrabold tracking-tight md:text-6xl">{pt?"Encontre empresas. Crie oportunidades. Faça negócios.":"Find companies. Create opportunities. Do business."}</h1><p className="mt-6 max-w-2xl text-lg text-blue-50">{pt?"Descubra fornecedores, publique necessidades e compare propostas numa única plataforma.":"Discover suppliers, publish needs and compare proposals in one platform."}</p><div className="mt-8 flex flex-wrap gap-3"><Link to="/directory" className="rounded-xl bg-white px-5 py-3 font-semibold text-blue-700">{pt?"Explorar empresas":"Explore companies"} <ArrowRight className="ml-1 inline" size={17}/></Link><Link to="/register" className="rounded-xl border border-white/40 px-5 py-3 font-semibold">{pt?"Criar conta":"Create account"}</Link></div></div>
   <div className="rounded-3xl bg-white p-6 text-slate-900 shadow-2xl"><div className="flex items-center gap-3"><div className="rounded-xl bg-blue-50 p-3 text-blue-700"><Search/></div><div><h2 className="font-bold">{pt?"O que precisa?":"What do you need?"}</h2><p className="text-sm text-slate-500">{pt?"Descreva a necessidade e encontre fornecedores compatíveis.":"Describe your need and find compatible suppliers."}</p></div></div><div className="mt-5 space-y-3">{["Fornecedor de serviços","Produtos e materiais","Consultoria","Tecnologia"].map(x=><Link key={x} to="/requests/new" className="flex items-center justify-between rounded-xl border p-4 hover:border-blue-300 hover:bg-blue-50"><span>{x}</span><ArrowRight size={17}/></Link>)}</div></div>
  </div></section>
  <section className="mx-auto max-w-7xl px-4 py-16"><p className="text-sm font-bold uppercase tracking-widest text-blue-600">{pt?"Como funciona":"How it works"}</p><h2 className="mt-2 text-3xl font-bold">{pt?"Do pedido à proposta em poucos passos":"From request to proposal in a few steps"}</h2><div className="mt-10 grid gap-5 md:grid-cols-3">{[[FileText,"1. Publique", "Descreva o que procura."],[Search,"2. Descubra","Receba fornecedores compatíveis."],[CheckCircle2,"3. Compare","Convide empresas e compare propostas."]].map(([Icon,title,desc])=><div key={title as string} className="rounded-2xl border bg-white p-6"><Icon as any className="text-blue-600"/><h3 className="mt-4 font-bold">{title as string}</h3><p className="mt-2 text-sm text-slate-600">{desc as string}</p></div>)}</div></section>
  <section className="border-y bg-white"><div className="mx-auto grid max-w-7xl gap-4 px-4 py-14 md:grid-cols-3"><div className="rounded-2xl bg-slate-50 p-6"><Building2 className="text-blue-600"/><h3 className="mt-4 font-bold">Diretório empresarial</h3><p className="mt-2 text-sm text-slate-600">Pesquise por sector, província e verificação.</p></div><div className="rounded-2xl bg-slate-50 p-6"><CheckCircle2 className="text-blue-600"/><h3 className="mt-4 font-bold">Perfis verificados</h3><p className="mt-2 text-sm text-slate-600">Identifique empresas com informação verificada.</p></div><div className="rounded-2xl bg-slate-50 p-6"><Users className="text-blue-600"/><h3 className="mt-4 font-bold">Rede B2B</h3><p className="mt-2 text-sm text-slate-600">Crie relações comerciais num só lugar.</p></div></div></section>
 </main>
}