import { createFileRoute, Link } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import { provinces, sectors } from "../lib/concept-data";

export const Route = createFileRoute("/requests/new")({ component: NewRequest });

function NewRequest() {
  const [title,setTitle]=useState(""); const [sector,setSector]=useState(sectors[0]); const [province,setProvince]=useState(provinces[0]);
  const [budget,setBudget]=useState(""); const [summary,setSummary]=useState(""); const [terms,setTerms]=useState("");
  const [participationMode,setParticipationMode]=useState<"open"|"qualified"|"invite_only">("open");
  const [requireVerified,setRequireVerified]=useState(false); const [minYears,setMinYears]=useState(""); const [minProjects,setMinProjects]=useState("");
  const [certifications,setCertifications]=useState(""); const [experience,setExperience]=useState(""); const [qualificationNote,setQualificationNote]=useState("");
  const [documentAccess,setDocumentAccess]=useState<"none"|"free"|"paid">("none"); const [documentPrice,setDocumentPrice]=useState(""); const [currency,setCurrency]=useState("MZN"); const [paymentInstructions,setPaymentInstructions]=useState("");
  const [file,setFile]=useState<File|null>(null); const [advanced,setAdvanced]=useState(false); const [invites,setInvites]=useState(false); const [done,setDone]=useState(false); const [error,setError]=useState("");

  useEffect(()=>{ supabase.auth.getUser().then(async ({data})=>{ if(!data.user)return; const {data:m}=await supabase.from("account_modules").select("advanced_qualification_enabled,supplier_invites_enabled").eq("user_id",data.user.id).maybeSingle(); setAdvanced(Boolean(m?.advanced_qualification_enabled)); setInvites(Boolean(m?.supplier_invites_enabled)); }); },[]);

  async function submit(event:React.FormEvent){event.preventDefault();setError("");const {data:userData}=await supabase.auth.getUser();if(!userData.user){setError("Entre na sua conta para criar um pedido.");return;}
    if(participationMode!=="open"&&!advanced){setError("A qualificação avançada é um módulo adicional.");return;} if(participationMode==="invite_only"&&!invites){setError("Os convites direccionados são um addon.");return;}
    if(documentAccess==="paid" && (!documentPrice || Number(documentPrice)<=0)){setError("Indique o preço do acesso aos documentos.");return;}
    const {data:req,error:e}=await supabase.from("requests").insert({owner_id:userData.user.id,title,sector,province,budget:budget||null,description:summary,tender_summary:summary,terms_content:terms||null,participation_mode:participationMode,require_verified:advanced?requireVerified:false,min_years_in_market:advanced&&minYears?Number(minYears):null,min_completed_projects:advanced&&minProjects?Number(minProjects):null,required_certifications:advanced?certifications.split(",").map(x=>x.trim()).filter(Boolean):[],required_experience:advanced?(experience||null):null,qualification_note:advanced?(qualificationNote||null):null,document_access:documentAccess,document_price:documentAccess==="paid"?Number(documentPrice):null,document_currency:documentAccess==="paid"?currency:null,payment_instructions:documentAccess==="paid"?paymentInstructions:null}).select("id").single();
    if(e||!req){setError(e?.message||"Não foi possível criar o processo.");return;}
    if(file){const path=`requests/${req.id}/documents/${Date.now()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"_")}`;const {error:uploadError}=await supabase.storage.from("request-documents").upload(path,file,{upsert:false});if(uploadError){setError(uploadError.message);return;}const {error:docError}=await supabase.from("request_documents").insert({request_id:req.id,owner_id:userData.user.id,file_name:file.name,storage_path:path,file_size:file.size,mime_type:file.type,is_public:documentAccess==="free"});if(docError){setError(docError.message);return;}}
    setDone(true);
  }
  if(done)return <main className="mx-auto max-w-2xl px-4 py-16 text-center"><div className="rounded-2xl border border-slate-200 bg-white p-10 shadow-sm"><h1 className="text-3xl font-bold text-[#102a43]">Processo criado</h1><p className="mt-3 text-slate-600">O resumo foi publicado e a documentação ficou configurada para acesso {documentAccess==="none"?"sem documentos":"conforme a regra escolhida"}.</p><Link to="/requests" className="mt-6 inline-block rounded-lg bg-[#0f766e] px-5 py-3 font-semibold text-white">Ver oportunidades</Link></div></main>;
  return <main className="mx-auto max-w-3xl px-4 py-12"><h1 className="text-3xl font-bold text-[#102a43]">Criar concurso ou necessidade</h1><p className="mt-2 text-slate-600">Pode começar de forma informal ou estruturar um processo com Termos de Referência e documentação própria.</p>
  <form onSubmit={submit} className="mt-8 space-y-6 rounded-2xl border border-slate-200 bg-white p-7 shadow-sm">
    <label className="field-label">Título<input required value={title} onChange={e=>setTitle(e.target.value)} className="field"/></label>
    <div className="grid gap-4 md:grid-cols-2"><label className="field-label">Sector<select className="field" value={sector} onChange={e=>setSector(e.target.value)}>{sectors.map(x=><option key={x}>{x}</option>)}</select></label><label className="field-label">Província<select className="field" value={province} onChange={e=>setProvince(e.target.value)}>{provinces.map(x=><option key={x}>{x}</option>)}</select></label></div>
    <label className="field-label">Resumo do concurso / necessidade<textarea required value={summary} onChange={e=>setSummary(e.target.value)} className="field min-h-40" placeholder="Cole ou escreva aqui o resumo que pretende tornar público."/></label>
    <label className="field-label">Termos de Referência / instruções<textarea value={terms} onChange={e=>setTerms(e.target.value)} className="field min-h-32" placeholder="Opcional: regras, critérios, entregáveis, prazos..."/></label>
    <label className="field-label">Orçamento<input value={budget} onChange={e=>setBudget(e.target.value)} className="field" placeholder="Opcional"/></label>
    <section className="rounded-2xl border border-slate-200 bg-[#f8fafc] p-5"><h2 className="font-extrabold text-[#102a43]">Documentação própria</h2><p className="mt-1 text-sm text-slate-600">Faça upload dos TdRs, cadernos, especificações ou outros documentos que queira disponibilizar aos participantes.</p>
      <label className="field-label mt-4">Ficheiro<input type="file" onChange={e=>setFile(e.target.files?.[0]??null)} className="field"/></label>
      <div className="mt-4 grid gap-3 md:grid-cols-3"><label className="flex gap-2 rounded-xl border bg-white p-3"><input type="radio" checked={documentAccess==="none"} onChange={()=>setDocumentAccess("none")}/><span><b>Sem documento</b><small className="block text-slate-500">Apenas o resumo.</small></span></label><label className="flex gap-2 rounded-xl border bg-white p-3"><input type="radio" checked={documentAccess==="free"} onChange={()=>setDocumentAccess("free")}/><span><b>Gratuito</b><small className="block text-slate-500">Qualquer participante elegível acede.</small></span></label><label className="flex gap-2 rounded-xl border bg-white p-3"><input type="radio" checked={documentAccess==="paid"} onChange={()=>setDocumentAccess("paid")}/><span><b>Pago</b><small className="block text-slate-500">Pagamento + comprovativo + aprovação.</small></span></label></div>
      {documentAccess==="paid"&&<div className="mt-4 space-y-4 rounded-xl bg-white p-4"><div className="grid gap-4 md:grid-cols-2"><label className="field-label">Preço<input required type="number" min="0.01" step="0.01" value={documentPrice} onChange={e=>setDocumentPrice(e.target.value)} className="field"/></label><label className="field-label">Moeda<select className="field" value={currency} onChange={e=>setCurrency(e.target.value)}><option>MZN</option><option>USD</option><option>ZAR</option><option>EUR</option></select></label></div><label className="field-label">Canais / instruções de pagamento<textarea required value={paymentInstructions} onChange={e=>setPaymentInstructions(e.target.value)} className="field min-h-24" placeholder="Conta, carteira móvel, referência, contacto..."/></label></div>}
    </section>
    <section className="rounded-2xl border border-slate-200 bg-[#f8fafc] p-5"><h2 className="font-extrabold text-[#102a43]">Participação</h2><p className="mt-1 text-sm text-slate-600">Defina se a oportunidade é aberta, qualificada ou limitada a convidados.</p>
      <div className="mt-4 grid gap-3"><label className="flex gap-3 rounded-xl border bg-white p-4"><input type="radio" checked={participationMode==="open"} onChange={()=>setParticipationMode("open")}/><span><b>Aberta</b><span className="block text-sm text-slate-500">Empresas compatíveis podem manifestar interesse.</span></span></label><label className="flex gap-3 rounded-xl border bg-white p-4"><input type="radio" checked={participationMode==="qualified"} onChange={()=>setParticipationMode("qualified")}/><span><b>Qualificada</b><span className="block text-sm text-slate-500">Aplica critérios adicionais.</span></span></label><label className="flex gap-3 rounded-xl border bg-white p-4"><input type="radio" checked={participationMode==="invite_only"} onChange={()=>setParticipationMode("invite_only")}/><span><b>Por convite</b><span className="block text-sm text-slate-500">Só convidados podem concorrer.</span></span></label></div>
      {advanced&&<div className="mt-4 space-y-4 rounded-xl border border-slate-200 bg-white p-4"><label className="flex gap-3 text-sm"><input type="checkbox" checked={requireVerified} onChange={e=>setRequireVerified(e.target.checked)}/><span><b>Apenas empresas verificadas</b></span></label><div className="grid gap-4 md:grid-cols-2"><label className="field-label">Anos mínimos no mercado<input type="number" min="0" value={minYears} onChange={e=>setMinYears(e.target.value)} className="field"/></label><label className="field-label">Projectos concluídos mínimos<input type="number" min="0" value={minProjects} onChange={e=>setMinProjects(e.target.value)} className="field"/></label></div><label className="field-label">Certificações exigidas<input value={certifications} onChange={e=>setCertifications(e.target.value)} className="field"/></label><label className="field-label">Experiência específica<textarea value={experience} onChange={e=>setExperience(e.target.value)} className="field"/></label><label className="field-label">Nota aos fornecedores<textarea value={qualificationNote} onChange={e=>setQualificationNote(e.target.value)} className="field"/></label></div>}
    </section>
    {error&&<p className="text-sm text-red-700">{error}</p>}<button className="w-full rounded-lg bg-[#0f766e] py-3 font-semibold text-white">Publicar processo</button>
  </form></main>;
}